runtime: nodejs
env: flex
manual_scaling:
  instances: 1
# instance_class: F2

env_variables:
  # BUCKET_NAME: "example-gcs-bucket"
  NODE_ENV: "production"

# handlers:
# - url: /stylesheets
#   static_dir: stylesheets
#
# - url: /.*
#   secure: always
#   redirect_http_response_code: 301
#   script: auto

resources:
  cpu: 0.5
  memory_gb: 0.18
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
