runtime: nodejs
env: flex
manual_scaling:
  instances: 1

env_variables:
  NODE_ENV: "production"

resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
